import axios from 'axios';
import {xml2js} from "xml-js";

const API_URL = 'https://fehupay.com/xml'; // Замість цього URL використовуйте свій бекенд

const data = {
        "items": [
        {
            "from": "PMUSD",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.95510984,
            "amount": 57310.56,
            "minamount": "5 USD",
            "maxamount": "1000000 USD",
            "url": "https://fehupay.com/exchange/PMUSD-NIXUSD",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.01020408,
            "amount": 57310.56,
            "minamount": "500 RUB",
            "maxamount": "50000 RUB",
            "url": "https://fehupay.com/exchange/PRRUB-NIXUSD",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.97847358,
            "amount": 57310.56,
            "minamount": "10 USD",
            "maxamount": "1000000 USD",
            "url": "https://fehupay.com/exchange/PRUSD-NIXUSD",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.01075265,
            "amount": 57310.56,
            "minamount": "3000 RUB",
            "maxamount": "90000 RUB",
            "url": "https://fehupay.com/exchange/SBERRUB-NIXUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "P24UAH",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.02347418,
            "amount": 57310.56,
            "minamount": "500 UAH",
            "maxamount": "30000 UAH",
            "url": "https://fehupay.com/exchange/P24UAH-NIXUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "USDTTRC20",
            "to": "NIXUSD",
            "in": 1,
            "out": 1,
            "amount": 57310.56,
            "minamount": "50 USDTTRC20",
            "maxamount": "10000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-NIXUSD",
            "param": "manual"
        },
        {
            "from": "SBPRUB",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.01075265,
            "amount": 57310.56,
            "minamount": "10000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-NIXUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "PSBRUB",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.00999033,
            "amount": 57310.56,
            "minamount": "3000 RUB",
            "maxamount": "90000 RUB",
            "url": "https://fehupay.com/exchange/PSBRUB-NIXUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "ABUAH",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.02300966,
            "amount": 57310.56,
            "minamount": "4000 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-NIXUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.01075265,
            "amount": 57310.56,
            "minamount": "500 RUB",
            "maxamount": "50000 RUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-NIXUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "NIXUSD",
            "in": 1,
            "out": 0.01075265,
            "amount": 57310.56,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-NIXUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "PMUSD",
            "in": 1,
            "out": 1.0033,
            "amount": 7457.6,
            "minamount": "5 USD",
            "maxamount": "10050 USD",
            "url": "https://fehupay.com/exchange/NIXUSD-PMUSD",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "PMUSD",
            "in": 1,
            "out": 0.01036283,
            "amount": 7457.6,
            "minamount": "500 PRRUB",
            "maxamount": "500000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-PMUSD",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "PMUSD",
            "in": 1,
            "out": 0.99762759,
            "amount": 7457.6,
            "minamount": "5 USD",
            "maxamount": "10050 USD",
            "url": "https://fehupay.com/exchange/PRUSD-PMUSD",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "PMUSD",
            "in": 1,
            "out": 0.010881,
            "amount": 7457.6,
            "minamount": "10000 RUB",
            "maxamount": "90000 RUB",
            "url": "https://fehupay.com/exchange/SBERRUB-PMUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "P24UAH",
            "to": "PMUSD",
            "in": 1,
            "out": 0.0233331,
            "amount": 7457.6,
            "minamount": "4000 UAH",
            "maxamount": "20000 UAH",
            "url": "https://fehupay.com/exchange/P24UAH-PMUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "USDTTRC20",
            "to": "PMUSD",
            "in": 1,
            "out": 1.002065,
            "amount": 7457.6,
            "minamount": "50 USDTTRC20",
            "maxamount": "10050 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-PMUSD",
            "param": "manual"
        },
        {
            "from": "SBPRUB",
            "to": "PMUSD",
            "in": 1,
            "out": 0.01085466,
            "amount": 7457.6,
            "minamount": "10000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-PMUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "PSBRUB",
            "to": "PMUSD",
            "in": 1,
            "out": 0.010846,
            "amount": 7457.6,
            "minamount": "10000 PSBRUB",
            "maxamount": "90000 PSBRUB",
            "url": "https://fehupay.com/exchange/PSBRUB-PMUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "ABUAH",
            "to": "PMUSD",
            "in": 1,
            "out": 0.02331534,
            "amount": 7457.6,
            "minamount": "4000 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-PMUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "PMUSD",
            "in": 1,
            "out": 0.01081712,
            "amount": 7457.6,
            "minamount": "5000 RNKBRUB",
            "maxamount": "50000 RNKBRUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-PMUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "PMUSD",
            "in": 1,
            "out": 0.01083528,
            "amount": 7457.6,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-PMUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "PRUSD",
            "in": 1,
            "out": 1.0061,
            "amount": 8587.3,
            "minamount": "5 USD",
            "maxamount": "10100 USD",
            "url": "https://fehupay.com/exchange/NIXUSD-PRUSD",
            "param": "manual"
        },
        {
            "from": "PMUSD",
            "to": "PRUSD",
            "in": 1,
            "out": 0.98049614,
            "amount": 8587.3,
            "minamount": "10 USD",
            "maxamount": "10100 USD",
            "url": "https://fehupay.com/exchange/PMUSD-PRUSD",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "PRUSD",
            "in": 1,
            "out": 0.01013216,
            "amount": 8587.3,
            "minamount": "3000 PRRUB",
            "maxamount": "20000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-PRUSD",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "PRUSD",
            "in": 1,
            "out": 0.01085601,
            "amount": 8587.3,
            "minamount": "10000 RUB",
            "maxamount": "90000 RUB",
            "url": "https://fehupay.com/exchange/SBERRUB-PRUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "P24UAH",
            "to": "PRUSD",
            "in": 1,
            "out": 0.02298111,
            "amount": 8587.3,
            "minamount": "4000 UAH",
            "maxamount": "20000 UAH",
            "url": "https://fehupay.com/exchange/P24UAH-PRUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "USDTTRC20",
            "to": "PRUSD",
            "in": 1,
            "out": 1.01140101,
            "amount": 8587.3,
            "minamount": "50 USDTTRC20",
            "maxamount": "10100 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-PRUSD",
            "param": "manual"
        },
        {
            "from": "SBPRUB",
            "to": "PRUSD",
            "in": 1,
            "out": 0.01078672,
            "amount": 8587.3,
            "minamount": "10000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-PRUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "PSBRUB",
            "to": "PRUSD",
            "in": 1,
            "out": 0.0108104,
            "amount": 8587.3,
            "minamount": "5000 PSBRUB",
            "maxamount": "90000 PSBRUB",
            "url": "https://fehupay.com/exchange/PSBRUB-PRUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "ABUAH",
            "to": "PRUSD",
            "in": 1,
            "out": 0.02284096,
            "amount": 8587.3,
            "minamount": "4000 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-PRUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "PRUSD",
            "in": 1,
            "out": 0.01078576,
            "amount": 8587.3,
            "minamount": "5000 RNKBRUB",
            "maxamount": "50000 RNKBRUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-PRUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "PRUSD",
            "in": 1,
            "out": 0.01078586,
            "amount": 8587.3,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-PRUSD",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "P24UAH",
            "in": 1,
            "out": 40.2,
            "amount": 103011.31,
            "minamount": "10 USD",
            "maxamount": "60000 USD",
            "url": "https://fehupay.com/exchange/NIXUSD-P24UAH",
            "param": "manual"
        },
        {
            "from": "PMUSD",
            "to": "P24UAH",
            "in": 1,
            "out": 38.76152366,
            "amount": 103011.31,
            "minamount": "50 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/PMUSD-P24UAH",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "P24UAH",
            "in": 1,
            "out": 0.41666667,
            "amount": 103011.31,
            "minamount": "4000 PRRUB",
            "maxamount": "500000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-P24UAH",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "P24UAH",
            "in": 1,
            "out": 39.2962,
            "amount": 103011.31,
            "minamount": "50 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/PRUSD-P24UAH",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "P24UAH",
            "in": 1,
            "out": 0.42735043,
            "amount": 103011.31,
            "minamount": "10000 SBERRUB",
            "maxamount": "90000 SBERRUB",
            "url": "https://fehupay.com/exchange/SBERRUB-P24UAH",
            "param": "manual, cardverify"
        },
        {
            "from": "USDTTRC20",
            "to": "P24UAH",
            "in": 1,
            "out": 40.2001,
            "amount": 103011.31,
            "minamount": "100 USDTTRC20",
            "maxamount": "20000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-P24UAH",
            "param": "manual"
        },
        {
            "from": "SBPRUB",
            "to": "P24UAH",
            "in": 1,
            "out": 0.419624,
            "amount": 103011.31,
            "minamount": "10000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-P24UAH",
            "param": "manual, cardverify"
        },
        {
            "from": "PSBRUB",
            "to": "P24UAH",
            "in": 1,
            "out": 0.41623735,
            "amount": 103011.31,
            "minamount": "5000 PSBRUB",
            "maxamount": "90000 PSBRUB",
            "url": "https://fehupay.com/exchange/PSBRUB-P24UAH",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "P24UAH",
            "in": 1,
            "out": 0.41123494,
            "amount": 103011.31,
            "minamount": "5000 RNKBRUB",
            "maxamount": "50000 RNKBRUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-P24UAH",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "P24UAH",
            "in": 1,
            "out": 0.41221815,
            "amount": 103011.31,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-P24UAH",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "MONOBUAH",
            "in": 1,
            "out": 40.2,
            "amount": 1924,
            "minamount": "10 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/NIXUSD-MONOBUAH",
            "param": "manual"
        },
        {
            "from": "PMUSD",
            "to": "MONOBUAH",
            "in": 1,
            "out": 38.9825,
            "amount": 1924,
            "minamount": "50 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/PMUSD-MONOBUAH",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "MONOBUAH",
            "in": 1,
            "out": 39.1269,
            "amount": 1924,
            "minamount": "50 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/PRUSD-MONOBUAH",
            "param": "manual"
        },
        {
            "from": "USDTTRC20",
            "to": "MONOBUAH",
            "in": 1,
            "out": 40.2001,
            "amount": 1924,
            "minamount": "100 USDTTRC20",
            "maxamount": "20000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-MONOBUAH",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "MONOBUAH",
            "in": 1,
            "out": 0.4239983,
            "amount": 1924,
            "minamount": "10000 SBERRUB",
            "maxamount": "90000 SBERRUB",
            "url": "https://fehupay.com/exchange/SBERRUB-MONOBUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "SBPRUB",
            "to": "MONOBUAH",
            "in": 1,
            "out": 0.41962168,
            "amount": 1924,
            "minamount": "10000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-MONOBUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "PRRUB",
            "to": "MONOBUAH",
            "in": 1,
            "out": 0.41668403,
            "amount": 1924,
            "minamount": "3500 PRRUB",
            "maxamount": "50000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-MONOBUAH",
            "param": "manual"
        },
        {
            "from": "PSBRUB",
            "to": "MONOBUAH",
            "in": 1,
            "out": 0.40561369,
            "amount": 1924,
            "minamount": "5000 PSBRUB",
            "maxamount": "90000 PSBRUB",
            "url": "https://fehupay.com/exchange/PSBRUB-MONOBUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "MONOBUAH",
            "in": 1,
            "out": 0.39235689,
            "amount": 1924,
            "minamount": "5000 RNKBRUB",
            "maxamount": "50000 RNKBRUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-MONOBUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "MONOBUAH",
            "in": 1,
            "out": 0.40301774,
            "amount": 1924,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-MONOBUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.99502488,
            "amount": 1485.1,
            "minamount": "200 USD",
            "maxamount": "10000 USD",
            "url": "https://fehupay.com/exchange/NIXUSD-USDTTRC20",
            "param": "manual"
        },
        {
            "from": "PMUSD",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.95831337,
            "amount": 1485.1,
            "minamount": "200 USD",
            "maxamount": "10000 USD",
            "url": "https://fehupay.com/exchange/PMUSD-USDTTRC20",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.01020409,
            "amount": 1485.1,
            "minamount": "20000 PRRUB",
            "maxamount": "500000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-USDTTRC20",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.97551458,
            "amount": 1485.1,
            "minamount": "200 USD",
            "maxamount": "10000 USD",
            "url": "https://fehupay.com/exchange/PRUSD-USDTTRC20",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.01079779,
            "amount": 1485.1,
            "minamount": "20000 RUB",
            "maxamount": "90000 RUB",
            "url": "https://fehupay.com/exchange/SBERRUB-USDTTRC20",
            "param": "manual, cardverify"
        },
        {
            "from": "P24UAH",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.02273864,
            "amount": 1485.1,
            "minamount": "8000 UAH",
            "maxamount": "30000 UAH",
            "url": "https://fehupay.com/exchange/P24UAH-USDTTRC20",
            "param": "manual, cardverify"
        },
        {
            "from": "SBPRUB",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.01080357,
            "amount": 1485.1,
            "minamount": "20000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-USDTTRC20",
            "param": "manual, cardverify"
        },
        {
            "from": "PSBRUB",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.01080489,
            "amount": 1485.1,
            "minamount": "20000 PSBRUB",
            "maxamount": "90000 PSBRUB",
            "url": "https://fehupay.com/exchange/PSBRUB-USDTTRC20",
            "param": "manual, cardverify"
        },
        {
            "from": "ABUAH",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.02263805,
            "amount": 1485.1,
            "minamount": "8500 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-USDTTRC20",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.01078818,
            "amount": 1485.1,
            "minamount": "20000 RNKBRUB",
            "maxamount": "50000 RNKBRUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-USDTTRC20",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "USDTTRC20",
            "in": 1,
            "out": 0.01080822,
            "amount": 1485.1,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-USDTTRC20",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "SBERRUB",
            "in": 1,
            "out": 87,
            "amount": 190492.88,
            "minamount": "100 USD",
            "maxamount": "24000 USD",
            "url": "https://fehupay.com/exchange/NIXUSD-SBERRUB",
            "param": "manual"
        },
        {
            "from": "PMUSD",
            "to": "SBERRUB",
            "in": 1,
            "out": 84.0001,
            "amount": 190492.88,
            "minamount": "100 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/PMUSD-SBERRUB",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "SBERRUB",
            "in": 1,
            "out": 0.91743961,
            "amount": 190492.88,
            "minamount": "10000 PRRUB",
            "maxamount": "500000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-SBERRUB",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "SBERRUB",
            "in": 1,
            "out": 85.9702,
            "amount": 190492.88,
            "minamount": "100 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/PRUSD-SBERRUB",
            "param": "manual"
        },
        {
            "from": "P24UAH",
            "to": "SBERRUB",
            "in": 1,
            "out": 1.9317,
            "amount": 190492.88,
            "minamount": "4000 P24UAH",
            "maxamount": "25000 P24UAH",
            "url": "https://fehupay.com/exchange/P24UAH-SBERRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "USDTTRC20",
            "to": "SBERRUB",
            "in": 1,
            "out": 88.0001,
            "amount": 190492.88,
            "minamount": "300 USDTTRC20",
            "maxamount": "20000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-SBERRUB",
            "param": "manual"
        },
        {
            "from": "ABUAH",
            "to": "SBERRUB",
            "in": 1,
            "out": 1.9101,
            "amount": 190492.88,
            "minamount": "4000 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-SBERRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "P24UAH",
            "to": "SBPRUB",
            "in": 1,
            "out": 1.987228,
            "amount": 8929.33,
            "minamount": "4000 P24UAH",
            "maxamount": "30000 P24UAH",
            "url": "https://fehupay.com/exchange/P24UAH-SBPRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "PMUSD",
            "to": "SBPRUB",
            "in": 1,
            "out": 83.6874,
            "amount": 8929.33,
            "minamount": "100 PMUSD",
            "maxamount": "10000 PMUSD",
            "url": "https://fehupay.com/exchange/PMUSD-SBPRUB",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "SBPRUB",
            "in": 1,
            "out": 85.88256647,
            "amount": 8929.33,
            "minamount": "50 PRUSD",
            "maxamount": "10000 PRUSD",
            "url": "https://fehupay.com/exchange/PRUSD-SBPRUB",
            "param": "manual"
        },
        {
            "from": "USDTTRC20",
            "to": "SBPRUB",
            "in": 1,
            "out": 88.36388078,
            "amount": 8929.33,
            "minamount": "100 USDTTRC20",
            "maxamount": "10000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-SBPRUB",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "SBPRUB",
            "in": 1,
            "out": 0.91751537,
            "amount": 8929.33,
            "minamount": "5000 PRRUB",
            "maxamount": "90000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-SBPRUB",
            "param": "manual"
        },
        {
            "from": "ABUAH",
            "to": "SBPRUB",
            "in": 1,
            "out": 2.0036881,
            "amount": 8929.33,
            "minamount": "4000 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-SBPRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "PRRUB",
            "in": 1,
            "out": 87,
            "amount": 695800.8,
            "minamount": "20 USD",
            "maxamount": "20000 USD",
            "url": "https://fehupay.com/exchange/NIXUSD-PRRUB",
            "param": "manual"
        },
        {
            "from": "PMUSD",
            "to": "PRRUB",
            "in": 1,
            "out": 83.98848,
            "amount": 695800.8,
            "minamount": "20 PMUSD",
            "maxamount": "20000 PMUSD",
            "url": "https://fehupay.com/exchange/PMUSD-PRRUB",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "PRRUB",
            "in": 1,
            "out": 85.9999,
            "amount": 695800.8,
            "minamount": "20 PRUSD",
            "maxamount": "20000 PRUSD",
            "url": "https://fehupay.com/exchange/PRUSD-PRRUB",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "PRRUB",
            "in": 1,
            "out": 0.98241478,
            "amount": 695800.8,
            "minamount": "10000 SBERRUB",
            "maxamount": "90000 SBERRUB",
            "url": "https://fehupay.com/exchange/SBERRUB-PRRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "P24UAH",
            "to": "PRRUB",
            "in": 1,
            "out": 2.019202,
            "amount": 695800.8,
            "minamount": "1500 P24UAH",
            "maxamount": "20000 P24UAH",
            "url": "https://fehupay.com/exchange/P24UAH-PRRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "USDTTRC20",
            "to": "PRRUB",
            "in": 1,
            "out": 87.9795,
            "amount": 695800.8,
            "minamount": "50 USDTTRC20",
            "maxamount": "10000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-PRRUB",
            "param": "manual"
        },
        {
            "from": "SBPRUB",
            "to": "PRRUB",
            "in": 1,
            "out": 0.98231827,
            "amount": 695800.8,
            "minamount": "10000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-PRRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "PSBRUB",
            "to": "PRRUB",
            "in": 1,
            "out": 0.98046311,
            "amount": 695800.8,
            "minamount": "5000 PSBRUB",
            "maxamount": "90000 PSBRUB",
            "url": "https://fehupay.com/exchange/PSBRUB-PRRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "ABUAH",
            "to": "PRRUB",
            "in": 1,
            "out": 2.030897,
            "amount": 695800.8,
            "minamount": "4000 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-PRRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "PRRUB",
            "in": 1,
            "out": 0.97018821,
            "amount": 695800.8,
            "minamount": "5000 RNKBRUB",
            "maxamount": "50000 RNKBRUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-PRRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "PRRUB",
            "in": 1,
            "out": 0.98222179,
            "amount": 695800.8,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-PRRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "PMUSD",
            "to": "PSBRUB",
            "in": 1,
            "out": 84.0001,
            "amount": 88480.32,
            "minamount": "100 PMUSD",
            "maxamount": "10000 PMUSD",
            "url": "https://fehupay.com/exchange/PMUSD-PSBRUB",
            "param": "manual"
        },
        {
            "from": "P24UAH",
            "to": "PSBRUB",
            "in": 1,
            "out": 1.950001,
            "amount": 88480.32,
            "minamount": "4000 P24UAH",
            "maxamount": "30000 P24UAH",
            "url": "https://fehupay.com/exchange/P24UAH-PSBRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "PSBRUB",
            "in": 1,
            "out": 87,
            "amount": 88480.32,
            "minamount": "50 NIXUSD",
            "maxamount": "10000 NIXUSD",
            "url": "https://fehupay.com/exchange/NIXUSD-PSBRUB",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "PSBRUB",
            "in": 1,
            "out": 85.85275145,
            "amount": 88480.32,
            "minamount": "50 PRUSD",
            "maxamount": "10000 PRUSD",
            "url": "https://fehupay.com/exchange/PRUSD-PSBRUB",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "PSBRUB",
            "in": 1,
            "out": 0.91628395,
            "amount": 88480.32,
            "minamount": "10000 PRRUB",
            "maxamount": "500000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-PSBRUB",
            "param": "manual"
        },
        {
            "from": "USDTTRC20",
            "to": "PSBRUB",
            "in": 1,
            "out": 87.9355,
            "amount": 88480.32,
            "minamount": "100 USDTTRC20",
            "maxamount": "10000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-PSBRUB",
            "param": "manual"
        },
        {
            "from": "ABUAH",
            "to": "PSBRUB",
            "in": 1,
            "out": 1.950011,
            "amount": 88480.32,
            "minamount": "4000 ABUAH",
            "maxamount": "20000 ABUAH",
            "url": "https://fehupay.com/exchange/ABUAH-PSBRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "PMUSD",
            "to": "MIRCRUB",
            "in": 1,
            "out": 83.7035,
            "amount": 87715,
            "minamount": "200 PMUSD",
            "maxamount": "10000 PMUSD",
            "url": "https://fehupay.com/exchange/PMUSD-MIRCRUB",
            "param": "manual"
        },
        {
            "from": "P24UAH",
            "to": "MIRCRUB",
            "in": 1,
            "out": 2.0015403,
            "amount": 87715,
            "minamount": "6000 P24UAH",
            "maxamount": "25000 P24UAH",
            "url": "https://fehupay.com/exchange/P24UAH-MIRCRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "NIXUSD",
            "to": "MIRCRUB",
            "in": 1,
            "out": 87,
            "amount": 87715,
            "minamount": "200 NIXUSD",
            "maxamount": "10000 NIXUSD",
            "url": "https://fehupay.com/exchange/NIXUSD-MIRCRUB",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "MIRCRUB",
            "in": 1,
            "out": 85.85771142,
            "amount": 87715,
            "minamount": "200 PRUSD",
            "maxamount": "10000 PRUSD",
            "url": "https://fehupay.com/exchange/PRUSD-MIRCRUB",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "MIRCRUB",
            "in": 1,
            "out": 0.91751537,
            "amount": 87715,
            "minamount": "20000 PRRUB",
            "maxamount": "500000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-MIRCRUB",
            "param": "manual"
        },
        {
            "from": "USDTTRC20",
            "to": "MIRCRUB",
            "in": 1,
            "out": 87.8619,
            "amount": 87715,
            "minamount": "200 USDTTRC20",
            "maxamount": "10000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-MIRCRUB",
            "param": "manual"
        },
        {
            "from": "PMUSD",
            "to": "RNKBRUB",
            "in": 1,
            "out": 83.3602,
            "amount": 7803,
            "minamount": "100 PMUSD",
            "maxamount": "20000 PMUSD",
            "url": "https://fehupay.com/exchange/PMUSD-RNKBRUB",
            "param": "manual"
        },
        {
            "from": "P24UAH",
            "to": "RNKBRUB",
            "in": 1,
            "out": 2.0089,
            "amount": 7803,
            "minamount": "4000 P24UAH",
            "maxamount": "30000 P24UAH",
            "url": "https://fehupay.com/exchange/P24UAH-RNKBRUB",
            "param": "manual, cardverify"
        },
        {
            "from": "PRUSD",
            "to": "RNKBRUB",
            "in": 1,
            "out": 84.6402,
            "amount": 7803,
            "minamount": "100 PRUSD",
            "maxamount": "20000 PRUSD",
            "url": "https://fehupay.com/exchange/PRUSD-RNKBRUB",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "RNKBRUB",
            "in": 1,
            "out": 0.91008282,
            "amount": 7803,
            "minamount": "5000 PRRUB",
            "maxamount": "20000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-RNKBRUB",
            "param": "manual"
        },
        {
            "from": "USDTTRC20",
            "to": "RNKBRUB",
            "in": 1,
            "out": 87.947,
            "amount": 7803,
            "minamount": "100 USDTTRC20",
            "maxamount": "1000000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-RNKBRUB",
            "param": "manual"
        },
        {
            "from": "SBERRUB",
            "to": "ABUAH",
            "in": 1,
            "out": 0.42217019,
            "amount": 44203,
            "minamount": "10000 SBERRUB",
            "maxamount": "90000 SBERRUB",
            "url": "https://fehupay.com/exchange/SBERRUB-ABUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "SBPRUB",
            "to": "ABUAH",
            "in": 1,
            "out": 0.41962168,
            "amount": 44203,
            "minamount": "10000 SBPRUB",
            "maxamount": "90000 SBPRUB",
            "url": "https://fehupay.com/exchange/SBPRUB-ABUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "PMUSD",
            "to": "ABUAH",
            "in": 1,
            "out": 38.9801,
            "amount": 44203,
            "minamount": "50 PMUSD",
            "maxamount": "20000 PMUSD",
            "url": "https://fehupay.com/exchange/PMUSD-ABUAH",
            "param": "manual"
        },
        {
            "from": "NIXUSD",
            "to": "ABUAH",
            "in": 1,
            "out": 40.2,
            "amount": 44203,
            "minamount": "10 NIXUSD",
            "maxamount": "20000 NIXUSD",
            "url": "https://fehupay.com/exchange/NIXUSD-ABUAH",
            "param": "manual"
        },
        {
            "from": "PRUSD",
            "to": "ABUAH",
            "in": 1,
            "out": 39.12631359,
            "amount": 44203,
            "minamount": "50 PRUSD",
            "maxamount": "20000 PRUSD",
            "url": "https://fehupay.com/exchange/PRUSD-ABUAH",
            "param": "manual"
        },
        {
            "from": "PRRUB",
            "to": "ABUAH",
            "in": 1,
            "out": 0.40618688,
            "amount": 44203,
            "minamount": "5000 PRRUB",
            "maxamount": "500000 PRRUB",
            "url": "https://fehupay.com/exchange/PRRUB-ABUAH",
            "param": "manual"
        },
        {
            "from": "USDTTRC20",
            "to": "ABUAH",
            "in": 1,
            "out": 40.2001,
            "amount": 44203,
            "minamount": "100 USDTTRC20",
            "maxamount": "20000 USDTTRC20",
            "url": "https://fehupay.com/exchange/USDTTRC20-ABUAH",
            "param": "manual"
        },
        {
            "from": "PSBRUB",
            "to": "ABUAH",
            "in": 1,
            "out": 0.3923261,
            "amount": 44203,
            "minamount": "10000 PSBRUB",
            "maxamount": "90000 PSBRUB",
            "url": "https://fehupay.com/exchange/PSBRUB-ABUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "RNKBRUB",
            "to": "ABUAH",
            "in": 1,
            "out": 0.3923261,
            "amount": 44203,
            "minamount": "10000 RNKBRUB",
            "maxamount": "90000 RNKBRUB",
            "url": "https://fehupay.com/exchange/RNKBRUB-ABUAH",
            "param": "manual, cardverify"
        },
        {
            "from": "MIRCRUB",
            "to": "ABUAH",
            "in": 1,
            "out": 0.40539427,
            "amount": 44203,
            "minamount": "20000 MIRCRUB",
            "maxamount": "90000 MIRCRUB",
            "url": "https://fehupay.com/exchange/MIRCRUB-ABUAH",
            "param": "manual, cardverify"
        }
    ]
}
const getDirection =  () => {
    try {
        // const response = await axios.get(`${API_URL}`);
        // console.log(response.data);
        // const jsonResult = xml2js(response.data);
        // console.log(jsonResult);
        return data.items;
    } catch (error) {
        console.error('Error fetching currency data:', error);
        throw error;
    }
};

export default {
    getDirection
};